### ISSUE TITLE
[visual-recognition] resolved_url removes required token query parameter

### ISSUE THREAD

**Issue by sdgandhi** [watson-developer-cloud/node-sdk#594]
### Steps to reproduce
I'm using both the URL and images_files method of supplying images.

```
            let parameters = {
                url: imageUrl,
                classifier_ids: ["technology_1628433143", "default"],
                threshold: 0.9
            };

            const tempFilePath = path.join(os.tmpdir(), "image.jpg");
            let tempImage = Request.get(imageUrl).pipe(fs.createWriteStream(tempFilePath));
            let readTempImage = fs.createReadStream("./airpods.jpeg");

            let classifyParameters = {
                parameters: parameters,
                images_file: readTempImage
            };

            visualRecognition.classify(classifyParameters, (err, resp) => {
                ...
            });
```

The images_files one works correctly, but the URL one has a problem: the resolved_url is missing a required token query parameter, therefore is not usable. This is what's returned from Watson:

```
        {
            "source_url": ".../images%2Fcapture-ZvVrsdR1PheW8TCkjlYkaMRYB0v1-2017-12-13T01:19:45.547847Z.jpg?alt=media&token=6f737b95-1c07-4db3-a1a3-63677ea3022e",
            "resolved_url": ".../images/capture-ZvVrsdR1PheW8TCkjlYkaMRYB0v1-2017-12-13T01:19:45.547847Z.jpg?alt=media",
            "error": {
                "code": 400,
                "description": "Failed fetching URL [.../images%2Fcapture-ZvVrsdR1PheW8TCkjlYkaMRYB0v1-2017-12-13T01:19:45.547847Z.jpg?alt=media&token=6f737b95-1c07-4db3-a1a3-63677ea3022e].",
                "error_id": "input_error"
            }
        }
```

Yes it will fail to fetch the URL without the token parameter.

### Expected behavior
I expect the URL to not change, thereby keeping the token parameter and making the fetch succeed.

### Actual behavior
The URL is changed and a required query parameter is removed in the resolved_url.

### Node version
v6.11.2

### SDK version
3.0.3

**Comment by anweshan** [comment]
Hi, thanks for notifying! This is a bug in the visual recognition service and they are actively looking into it to fix this issue.

**Comment by mtucker01752** [comment]
I think I understand what the problem is. I need to do some more testing to make sure the various cases are covered.

**Comment by mtucker01752** [comment]
The fix is deployed to PPRD.

**Comment by doct0r** [comment]
I have a similar issue that I think is related to this. In my case the part after '&' is removed (or encoded wrongly) and the image cannot be found. An example image is this one: https://scontent-ams3-1.xx.fbcdn.net/v/t34.0-12/25359726_10156020758255742_120248478_n.png?oh=930c046fadce3cced1ef31e8b07fb022&oe=5A33BE37

The response is `{
    "images": [
        {
            "source_url": "https://scontent-ams3-1.xx.fbcdn.net/v/t34.0-12/25359726_10156020758255742_120248478_n.png?oh=930c046fadce3cced1ef31e8b07fb022",
            "resolved_url": "https://scontent-ams3-1.xx.fbcdn.net/v/t34.0-12/25359726_10156020758255742_120248478_n.png?oh=930c046fadce3cced1ef31e8b07fb022",
            "error": {
                "code": 400,
                "description": "request to fetch blocked: disallowed",
                "error_id": "input_error"
            }
        }
    ],
    "images_processed": 1
}`
I've tested this after @mtucker01752 mentioned there is a fix and it still occurs.

**Comment by mtucker01752** [comment]
@doct0r This is my interpretation of the issue you are seeing. I'm working to confirm the robots.txt behavior with the developers of the URL Fetcher code.

This looks like a separate issue. I tried that URL and I see that it is now being encoded correctly. (The fix we deployed yesterday addressed the encoding problem.)

```
{
    "images": [
        {
            "source_url": "https://scontent-ams3-1.xx.fbcdn.net/v/t34.0-12/25359726_10156020758255742_120248478_n.png?oh=930c046fadce3cced1ef31e8b07fb022&oe=5A33BE37",
            "resolved_url": "https://scontent-ams3-1.xx.fbcdn.net/v/t34.0-12/25359726_10156020758255742_120248478_n.png?oh=930c046fadce3cced1ef31e8b07fb022&oe=5A33BE37",
            "error": {
                "code": 400,
                "description": "request to fetch blocked: disallowed",
                "error_id": "input_error"
            }
        }
    ],
    "images_processed": 1
}
```

The error you are getting now is: `"request to fetch blocked: disallowed"`.  This is happening because the site's robots.txt file (https://scontent-ams3-1.xx.fbcdn.net/robots.txt) says:
```
User-agent: *
Disallow: /
```

...which disallows all "robots" (including our URL fetching code) from accessing the site.

**Comment by doct0r** [comment]
@mtucker01752 Is the fix deployed in UK region? Cause I'm still seeing the wrong URL being resolved.

Keep in mind that this worked until Tuesday and I understand that this is when this URL bug was deployed, so it would be quite the coincidence :)

**Comment by mtucker01752** [comment]
@doct0r The Visual Recognition service is syndicated in the UK region, which means that the service instance itself is in us-south, which is where the fix was deployed.

Can you clarify how you are calling the service and passing the URL? Are you doing a direct GET or POST? Are you using one of the SDK's?

**Comment by doct0r** [comment]
@mtucker01752 Doing a GET request. Something like this: https://gateway-a.watsonplatform.net/visual-recognition/api/v3/classify?api_key=<API_KEY>&url=https://scontent-ams3-1.xx.fbcdn.net/v/t34.0-12/25359726_10156020758255742_120248478_n.png?oh=930c046fadce3cced1ef31e8b07fb022&oe=5A33BE37&version=2016-05-19&classifier_ids=<CUSTOM_CLASSIFIER>,default&threshold=0.5

**Comment by mtucker01752** [comment]
@doct0r Ah - ok. When doing a GET, you pass the URL as a query parameter. Because of this, you need to encode the URL- especially since it includes an `&`. Without encoding, we can't distinguish between where the URL ends and where the next VR-service query parameter begins. In short, we are interpreting `oe=5A33...` as its own query parameter.

Strictly speaking, I think you can get away with encoding just the `&` in the URL (since the other characters don't cause a problem), but it's safer and more proper to encode the entire URL.

So your request should be something like: ` https://gateway-a.watsonplatform.net/visual-recognition/api/v3/classify?api_key=<API_KEY>&url=https%3A%2F%2Fscontent-ams3-1.xx.fbcdn.net%2Fv%2Ft34.0-12%2F25359726_10156020758255742_120248478_n.png%3Foh%3D930c046fadce3cced1ef31e8b07fb022%26oe%3D5A33BE37&version=2016-05-19&classifier_ids=<CUSTOM_CLASSIFIER>,default&threshold=0.5`

Hope this helps.

(As noted above, I suspect that  you will still hit the "request to fetch blocked: disallowed" error due to that site's robots.txt file.)

**Comment by doct0r** [comment]
@mtucker01752 Sorry, I wasn't very clear before but we do encode the URL. I can now see that the encoding problem is gone and indeed we are still getting "request to fetch blocked: disallowed".

Could it be that the change on the URL fetching code makes it look like an agent while before it wasn't? It still seems a big coincidence for this to start the same day some changes were introduced to this module.

**Comment by mtucker01752** [comment]
@doct0r Thanks for that confirmation.

We are continuing conversations with the developers who wrote the URL Fetcher code. We have discovered that previous versions of that code did not honor the robots.txt settings, while the new code does honor that file. We're exploring what options we have available. I'll update here with any new info.

**Comment by mtucker01752** [comment]
The URL Fetcher has been updated in production with a fix for the robots.txt issue. Things should be good now.
